version: '3.1'

services:
    admin:
        image: node:16-alpine
        volumes:
            - "./:/app"
        user: 1000:1000
        working_dir: /app/app
        ports:
            - ${LOCAL_DEV_PORT}:3000
        command: sh -c "npm start"
    backend:
        image: node:16
        volumes:
            - "./dummy-backend:/backend"
        user: 1000:1000
        working_dir: /backend
        expose:
            - 5000
        command: bash -c "node index.js"